[tool.pytest.ini_options]
addopts = "--ignore=plugin/vendor"
markers = [
    "integration: mark a test as an integration test."
]

[tool.mypy]
exclude = "^plugin/vendor/|scripts/|tests/"
strict = true

[tool.ruff]
target-version = "py39"
select = ["E", "F", "B", "W", "I", "UP"]
ignore = []
line-length = 88
exclude = ["plugin/vendor", "scripts"]