name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read python version
        id: pyver
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.pyver.outputs.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run linter
        run: ruff check .
      - name: Run static type checks
        run: mypy .
      - name: Run unit tests
        run: pytest --disable-warnings
      - name: Run integration tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest --disable-warnings -m integration
